spring:
  application:
    name: ebank-admin
  security:
    user:
      name: ${ADMIN_UI_USER:admin}
      password: ${ADMIN_UI_PASSWORD:admin}

  boot:
    admin:
      server:
        enabled: true
      ui:
        title: eBank Admin
        brand: "<img src='assets/img/icon-spring-boot-admin.svg'><span>eBank Admin</span>"

server:
  port: ${SERVER_PORT:8090}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    de.codecentric: INFO
