{{- if .Values.accounts.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ebank.fullname" . }}-accounts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebank.labels" . | nindent 4 }}
    app.kubernetes.io/component: accounts
spec:
  {{- if not .Values.accounts.autoscaling.enabled }}
  replicas: {{ .Values.accounts.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ebank.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: accounts
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "ebank.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: accounts
      annotations:
        checksum/values: {{ .Values | toYaml | sha256sum | trunc 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      initContainers:
        {{- include "ebank.waitForVault" . | nindent 8 }}
      containers:
        - name: accounts
          image: {{ include "ebank.image" (dict "service" .Values.accounts "global" .Values.global) }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.accounts.port }}
              protocol: TCP
          env:
            {{- include "ebank.vaultEnv" . | nindent 12 }}
            {{- include "ebank.springProfileEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.accounts.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /actuator/health
              port: http
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 0
            periodSeconds: {{ .Values.accounts.probes.liveness.periodSeconds }}
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 0
            periodSeconds: {{ .Values.accounts.probes.readiness.periodSeconds }}
            failureThreshold: 3
            timeoutSeconds: 5
{{- end }}
