{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ebank.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ebank.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    {{- include "ebank.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
{{- end }}
