spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password:

error:
  handling:
    show-details: true
    include-stacktrace: false
    include-validation-errors: true
    include-trace-id: false
