spring:
  application:
    name: ebank-monolith
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      timeout: 2000ms

  kafka:
    enabled: false   # Override to true in docker/prod profiles to enable Kafka publishing

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"

error:
  handling:
    include-stacktrace: false
    include-trace-id: true
    show-details: false
    include-validation-errors: true
