spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ebank_db
    username: ebank
    password: ebank

  data:
    redis:
      host: redis
      port: 6379

  mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  kafka:
    enabled: true
    bootstrap-servers: kafka:9092

jwt:
  secret: ${JWT_SECRET:change-me-in-prod-min-256-bits-long-string}
  expiration: 900000
  refresh-expiration: 604800000

management:
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

logging:
  level:
    com.ebank: INFO
