-- ─────────────────────────────────────────────────────────────────────────────
-- V1__create_schema.sql
-- Initial schema: users, accounts, transactions
-- Compatible with PostgreSQL 13+ and H2 2.x (MODE=PostgreSQL)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── users ─────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name     VARCHAR(255),
    role          VARCHAR(50)  NOT NULL DEFAULT 'USER',
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ── accounts ──────────────────────────────────────────────────────────────────
CREATE TABLE accounts (
    id             BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT        NOT NULL,
    account_number VARCHAR(20)   NOT NULL,
    account_type   VARCHAR(50)   NOT NULL,
    balance        NUMERIC(15,2) NOT NULL DEFAULT 0,
    status         VARCHAR(50)   NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_accounts_account_number UNIQUE (account_number),
    CONSTRAINT fk_accounts_user           FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_accounts_user_id       ON accounts (user_id);
CREATE INDEX idx_accounts_account_number ON accounts (account_number);

-- ── transactions ──────────────────────────────────────────────────────────────
CREATE TABLE transactions (
    id               BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id  BIGINT        NOT NULL,
    to_account_id    BIGINT        NOT NULL,
    amount           NUMERIC(15,2) NOT NULL,
    transaction_type VARCHAR(50)   NOT NULL,
    status           VARCHAR(50)   NOT NULL DEFAULT 'PENDING',
    reference        VARCHAR(255),
    description      TEXT,
    created_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_transactions_reference UNIQUE (reference),
    CONSTRAINT fk_transactions_from      FOREIGN KEY (from_account_id) REFERENCES accounts (id),
    CONSTRAINT fk_transactions_to        FOREIGN KEY (to_account_id)   REFERENCES accounts (id)
);

CREATE INDEX idx_transactions_from_account ON transactions (from_account_id);
CREATE INDEX idx_transactions_to_account   ON transactions (to_account_id);
